// Fake RSS feed for pages that does not have RSS, guid is simply hash of the content
"use strict";
// globals: chrome, VP, DH

var RR = RR || {};
RR.rss = RR.rss || {};
RR.rss.recentXml = RR.rss.recentXml || null;

RR.rss.isNone = function () { // aUrl
    // this parser can be used anywhere
    return true;
};

RR.rss.parseNone = function (aText, aUrl) {
    // parse page
    var feed, item;
    RR.rss.recentXml = aText;

    // header
    feed = new RR.rss.feed('rss_none.js');
    feed.header = RR.rss.header();
    feed.header.title = 'RSS None';
    feed.header.description = 'RSS feed for pages that does not have RSS';
    feed.header.administrator = null;
    feed.header.generator = chrome.runtime.getManifest().name + '/RR.rss.parseRssNone';
    feed.header.link = null;

    // add RSS item
    item = RR.rss.item();
    item.title = 'Page changed: ' + aUrl;
    item.link = aUrl;
    item.date = new Date();
    item.guid = RR.rss.hash(aUrl + aText);
    item.description =
        '<div>RSS Reader detected change on this page: <a href="' + aUrl + '">' + aUrl + '</a> (length ' + aText.length + ')</div>' +
        '<br><div><b>NOTE:</b> this RSS item was generated by fallback parser which is used when normal RSS parsers failed. This is useful for pages that does not have RSS feed, but sometimes you see this message when the server failed. Because RSS reader cannot distinguish between no RSS feed and server error, in such case simply mark this item as read and try to refresh feed later.</div>';
    feed.items.push(item);

    return feed;
};

